config/routes.rb
Rails.application.routes.draw do
  resources :measurements
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/measurement.rb
class Measurement < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  before_action :set_measurement, only: %i[ show edit update destroy ]

  # GET /measurements or /measurements.json
  def index
    @measurements = Measurement.all
  end

  # GET /measurements/1 or /measurements/1.json
  def show
  end

  # GET /measurements/new
  def new
    @measurement = Measurement.new
  end

  # GET /measurements/1/edit
  def edit
  end

  # POST /measurements or /measurements.json
  def create
    @measurement = Measurement.new(measurement_params)

    respond_to do |format|
      if @measurement.save
        format.html { redirect_to @measurement, notice: "Measurement was successfully created." }
        format.json { render :show, status: :created, location: @measurement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measurements/1 or /measurements/1.json
  def update
    respond_to do |format|
      if @measurement.update(measurement_params)
        format.html { redirect_to @measurement, notice: "Measurement was successfully updated." }
        format.json { render :show, status: :ok, location: @measurement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurements/1 or /measurements/1.json
  def destroy
    @measurement.destroy!

    respond_to do |format|
      format.html { redirect_to measurements_path, status: :see_other, notice: "Measurement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measurement
      @measurement = Measurement.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def measurement_params
      params.expect(measurement: [ :dip, :strike, :latitude, :longitude ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Geo Data Collector" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/measurements/_form.html.erb
<%= form_with(model: measurement) do |form| %>
  <% if measurement.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(measurement.errors.count, "error") %> prohibited this measurement from being saved:</h2>

      <ul>
        <% measurement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :dip, style: "display: block" %>
    <%= form.text_field :dip %>
  </div>

  <div>
    <%= form.label :strike, style: "display: block" %>
    <%= form.text_field :strike %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/measurements/_measurement.html.erb
<div id="<%= dom_id measurement %>">
  <p>
    <strong>Dip:</strong>
    <%= measurement.dip %>
  </p>

  <p>
    <strong>Strike:</strong>
    <%= measurement.strike %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= measurement.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= measurement.longitude %>
  </p>

</div>

app/views/measurements/edit.html.erb
<% content_for :title, "Editing measurement" %>

<h1>Editing measurement</h1>

<%= render "form", measurement: @measurement %>

<br>

<div>
  <%= link_to "Show this measurement", @measurement %> |
  <%= link_to "Back to measurements", measurements_path %>
</div>

app/views/measurements/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Measurements" %>

<h1>Measurements</h1>

<div id="measurements">
  <% @measurements.each do |measurement| %>
    <%= render measurement %>
    <p>
      <%= link_to "Show this measurement", measurement %>
    </p>
  <% end %>
</div>

<%= link_to "New measurement", new_measurement_path %>

app/views/measurements/new.html.erb
<% content_for :title, "New measurement" %>

<h1>New measurement</h1>

<%= render "form", measurement: @measurement %>

<br>

<div>
  <%= link_to "Back to measurements", measurements_path %>
</div>

app/views/measurements/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @measurement %>

<div>
  <%= link_to "Edit this measurement", edit_measurement_path(@measurement) %> |
  <%= link_to "Back to measurements", measurements_path %>

  <%= button_to "Destroy this measurement", @measurement, method: :delete %>
</div>